### ISSUE TITLE
Can't export in Graphite.rs

### ISSUE THREAD

**Issue by tattbaku** [GraphiteEditor/Graphite#2165] opened 2024-12-28 08:45 UTC
Trying to export in Graphite.rs and it won't. The choice box appears but nothing happens. Tried since yesterday.

**Comment by Keavon** [comment] 2024-12-28 08:48
Please provide as much information as you can. What browser are you using? Did it work previously? Did you change anything in the interim? Have you attempted resetting things like rebooting your computer? Have you tested a different browser? A different document in Graphite?

**Comment by 0HyperCube** [comment] 2024-12-28 10:46
You have to press the export button in the dialogue box:
![export dialogue](https://github.com/user-attachments/assets/03a2e0c5-59b0-4b8e-b707-897fe6645e1e)

**Comment by tattbaku** [comment] 2024-12-28 11:54
Sigh....I did that.....wouldn't you...????????
    On Saturday 28 December 2024 at 10:46:47 GMT, James Lindsay ***@***.***> wrote:  
 
 


You have to press the export button in the dialogue box:
image.png (view on web)

**Comment by Keavon** [comment] 2024-12-28 11:55
I'm going to close this issue since it isn't reproducible or actionable. Thanks for the report and I hope some of the suggestions I listed earlier can help you resolve the problem on your end.

**Closed by Keavon** 2024-12-28 11:55 UTC

**Comment by tattbaku** [comment] 2024-12-28 12:39
Chrome, Windows 11 Pro, yes it worked last time I used it which was a couple of weeks ago, didn't change anything, have rebooted more than once. Did all of that, tried a different document, different browser.......nothing. Click 'export' and nothing happens. Can save, which I ended up doing and screenshotting then paste into another programme.
    On Saturday 28 December 2024 at 08:48:44 GMT, Keavon Chambers ***@***.***> wrote:  
 
 


Please provide as much information as you can. What browser and operating system are you using? Did it work previously? Did you change anything in the interim? Have you attempted resetting things like rebooting your computer? Have you tested a different browser? A different document in Graphite?

**Comment by Keavon** [comment] 2024-12-28 19:13
If a different browser (such as Firefox) didn't solve it, and you've tested other similar documents, then the problem is either with your OS's download dialog or something common to your system. All I can suggest to help you is to try another computer, and if that fixes it, you could reinstall your operating system in an extreme case. The issue isn't with Graphite, and if it's not with the browser either, the culprit is either the OS or something you're uniquely doing (or not doing), in terms of basic troubleshooting logic.

**Comment by tattbaku** [comment] 2024-12-29 11:29
Thanks, I'll keep on at it......
    On Saturday 28 December 2024 at 19:13:34 GMT, Keavon Chambers ***@***.***> wrote:  
 
 


If a different browser (such as Firefox) didn't solve it, and you've tested other similar documents, then the problem is either with your OS's download dialog or something common to your system. All I can suggest to help you is to try another computer, and if that fixes it, you could reinstall your operating system in an extreme case. The issue isn't with Graphite, and if it's not with the browser either, the culprit is either the OS or something you're uniquely doing (or not doing), in terms of basic troubleshooting logic.

**Comment by tattbaku** [comment] 2024-12-31 13:29
Not my OS as suddenly it works again! 

Yahoo Mail: Search, organise, conquer 
 
  On Sun, 29 Dec 2024 at 11:29, Pat ***@***.***> wrote:    Thanks, I'll keep on at it......
    On Saturday 28 December 2024 at 19:13:34 GMT, Keavon Chambers ***@***.***> wrote:  
 
 


If a different browser (such as Firefox) didn't solve it, and you've tested other similar documents, then the problem is either with your OS's download dialog or something common to your system. All I can suggest to help you is to try another computer, and if that fixes it, you could reinstall your operating system in an extreme case. The issue isn't with Graphite, and if it's not with the browser either, the culprit is either the OS or something you're uniquely doing (or not doing), in terms of basic troubleshooting logic.
