### ISSUE TITLE
Hide popups triggered by hovering after moving the cursor away

### ISSUE THREAD

**Issue by bjorn3** [GraphiteEditor/Graphite#598] opened 2022-04-21 16:59 UTC
They might block the thing you actually wanted to interact with.

https://user-images.githubusercontent.com/17426603/164512624-f5af3b76-9995-4767-a799-0dbd7897e221.mp4

**Comment by Keavon** [comment] 2022-04-21 17:03
This already happens if the mouse strays 100px away from the floating menu. Are you just suggesting that we reduce the stray distance?

https://github.com/GraphiteEditor/Graphite/blob/master/frontend/src/components/widgets/floating-menus/FloatingMenu.vue#L185

**Comment by 0HyperCube** [comment] 2022-04-21 17:03
> Hide popups triggered by hovering

@bjorn3 When are popups triggered by hovering?

**Comment by bjorn3** [comment] 2022-04-21 17:05
> This already happens if the mouse strays 100px away from the floating menu. Are you just suggesting that we reduce the stray distance?

When it is triggered by hovering I think it should hide as soon as you move to the left or right of it. Or not show up on hover at all. If you actually click on it 100px of stray space makes sense.

> @bjorn3 When are popups triggered by hovering?

I didn't click in the recording in the issue description.

**Comment by 0HyperCube** [comment] 2022-04-21 17:09
> I didn't click in the recording in the issue description.

Can't seem to reproduce this - can you give more details?

**Comment by Keavon** [comment] 2022-04-21 17:09
You're describing the behavior where drifting your mouse to a neighboring widget that creates a floating menu switches over to that floating menu? If that's the case, that behavior is only supposed to happen in limited circumstances (inspired by Blender) where you drift to horizontal neighboring widgets, like *File*, *Edit*, *Layer*, *Document*, *View*, *Help* as well as entries in the options bar or other horizontal layouts of related widgets. It shouldn't happen in different rows arranged vertically like in the properties panel.

**Comment by bjorn3** [comment] 2022-04-21 17:11
> Can't seem to reproduce this - can you give more details?

I just reloaded the page and can't reproduce it anymore either.

**Comment by bjorn3** [comment] 2022-04-21 17:13
> It shouldn't happen in different rows arranged vertically like in the properties panel.

I just tried this and it does happen for me when I click on style and then hover over font for like a second.


https://user-images.githubusercontent.com/17426603/164514754-5975c5bc-172a-4a46-91f3-ac46ab1cb700.mp4

**Comment by Keavon** [comment] 2022-04-21 17:15
> I just tried this and it does happen for me when I click on style and then hover over font for like a second.

Correct, that is one of many places where it inappropriately does that. If I recall correctly, I never finished my implementation which was supposed to restrict it to a common direct parent for sibling widgets.

**Comment by Keavon** [comment] 2022-04-21 17:22
@bjorn3 is that the root of the issue you reported here? I'd like to rename the issue if so, and file it in the next sprint.

**Comment by bjorn3** [comment] 2022-04-21 17:23
I think the root issue was graphite somehow getting stuck into thinking I had the left mouse button down or something like that. Reloading fixed it.

**Comment by Keavon** [comment] 2022-04-21 17:25
Were you running the live editor or running it locally? I think the bug you're describing, if I understand what you are saying, is caused by live reload.

**Comment by bjorn3** [comment] 2022-04-21 17:26
I was using https://editor.graphite.rs/

**Comment by Keavon** [comment] 2022-04-21 17:40
Ok. If you do manage to precisely reproduce it and list the steps, that would be awesome.

**Comment by bjorn3** [comment] 2022-04-21 18:03
Tried a couple of things. I can't reproduce this. Should I close the issue?

**Comment by Keavon** [comment] 2022-04-21 18:30
I think for now we should probably close it but if you end up finding more information, please feel free to reopen the issue in the future.

**Closed by Keavon** 2022-04-21 18:30 UTC
