### ISSUE TITLE
[Crash Report] changing the font size rapidly caused panic at 'FontInput update does not have a fontFamily' 

### ISSUE THREAD

**Issue by loopervfx** [GraphiteEditor/Graphite#1341] opened 2023-07-30 07:48 UTC
**Describe the Crash**
Explain clearly what you were doing when the crash occurred.

**Steps To Reproduce**
Describe precisely how the crash occurred, step by step, starting with a new editor window.
1. Open the Graphite Editor at https://editor.graphite.rs
2. create text
3. change the font size rapidly using increment arrow buttons
4. ...
5. crash???

**Additional Details**
Provide any further information or context that you think would be helpful in fixing the issue. Screenshots or video can be linked or attached to this issue.

**Browser and OS**
Chrome 114, Windows 10 or 11

**Stack Trace**
Copied from the crash dialog in the Graphite Editor:

```
panicked at 'FontInput update does not have a fontFamily', /var/lib/github-actions/_work/Graphite/Graphite/editor/src/messages/layout/layout_message_handler.rs:133:80

Error
    at https://editor.graphite.rs/index.2eff524e.js:25:3480
    at Object.handleJsMessage (https://editor.graphite.rs/index.2eff524e.js:17:46042)
    at https://editor.graphite.rs/index.2eff524e.js:17:63469
    at https://editor.graphite.rs/index.2eff524e.js:17:60425
    at Vr (https://editor.graphite.rs/index.2eff524e.js:17:48826)
    at Or.t.wbg.__wbg_call_96878afb7a8201ca (https://editor.graphite.rs/index.2eff524e.js:17:60387)
    at https://editor.graphite.rs/graphite_wasm_bg.6b952664.wasm:wasm-function[412]:0x1ccac7
    at https://editor.graphite.rs/graphite_wasm_bg.6b952664.wasm:wasm-function[2019]:0x2e14a4
    at https://editor.graphite.rs/graphite_wasm_bg.6b952664.wasm:wasm-function[1974]:0x2def06
    at https://editor.graphite.rs/graphite_wasm_bg.6b952664.wasm:wasm-function[3030]:0x30becf
    at https://editor.graphite.rs/graphite_wasm_bg.6b952664.wasm:wasm-function[3629]:0x3135d9
    at https://editor.graphite.rs/graphite_wasm_bg.6b952664.wasm:wasm-function[138]:0xf25da
    at https://editor.graphite.rs/graphite_wasm_bg.6b952664.wasm:wasm-function[2253]:0x2ec879
    at Dr.updateLayout (https://editor.graphite.rs/index.2eff524e.js:17:50253)
    at u (https://editor.graphite.rs/index.2eff524e.js:45:208473)
    at Array.<anonymous> (https://editor.graphite.rs/index.2eff524e.js:45:209008)
    at Su.<anonymous> (https://editor.graphite.rs/index.2eff524e.js:45:195881)
    at https://editor.graphite.rs/index.2eff524e.js:16:14714
    at Array.forEach (<anonymous>)
    at https://editor.graphite.rs/index.2eff524e.js:16:14699
    at https://editor.graphite.rs/index.2eff524e.js:45:180184
```

**Comment by 0HyperCube** [comment] 2023-08-04 17:35
I cannot replicate this issue @loopervfx. Does it reliably occur for you?

**Comment by 0HyperCube** [comment] 2023-12-18 11:28
Closing as I cannot reproduce this crash.

**Closed by 0HyperCube** 2023-12-18 11:28 UTC
Labels: Crash
