### ISSUE TITLE
Change origin reference point with 9-dot selector (not just for rotations)

### ISSUE THREAD

**Issue by tcpie** [GraphiteEditor/Graphite#2140] opened 2024-12-16 18:19 UTC
I noticed that the "9 dots" origin-selector only applies to rotations. In, e.g., Adobe Illustrator, this also affects translation and scaling (which I think is the expected behavior).

Could Graphite be updated so that the origin is also affected for translations?

See below screenshots that illustrate what I mean. The red and blue shape should not have the same X coordinate, as I selected the reference of origin to be center-left. (also notice how the "9 dot" selector is quite difficult to see, perhaps something to adjust as well).

![afbeelding](https://github.com/user-attachments/assets/21c2ddca-5bf5-4e65-9308-cbb0944963b3)
![afbeelding](https://github.com/user-attachments/assets/309b0292-7b08-4608-822c-9d926f2dbd2e)

**Comment by Keavon** [comment] 2024-12-16 18:24
Thanks for the report. This is a duplicate of #1530 (although that issue has some outdated information, so disregard any inaccuracies it may have).

**Closed by Keavon** 2024-12-16 18:24 UTC

**Comment by 0HyperCube** [comment] 2024-12-16 18:31
The yellow dot is not the origin, it is the centre of rotation.

**Comment by tcpie** [comment] 2024-12-16 18:34
Thanks for the quick follow up. My apologies, I did a quick search but missed that duplicate issue.

**Comment by Keavon** [comment] 2024-12-16 18:37
For some additional context, we have a large refactor planned for how the node graph encodes instance data and how those instances store their transforms. This will fundamentally change the limited system we currently have in place for transforms, largely with the aim of solving some of the outstanding issues like the one you pointed out. I hope it'll be done by Q1 2025.
