### ISSUE TITLE
Finalize the design of transforms using the Transform node

### ISSUE THREAD

**Issue by 0HyperCube** [GraphiteEditor/Graphite#534] opened 2022-02-10 21:37 UTC
Possibly we need to redesign transform system. To address:
- Folders have transforms?
- Showing skew in properties panel
- Non-affine perspective transforms (dragging each corner of the bounding box to an arbitrary place, except concave)
- Inconsistent behaviour between lines / polylines and other shapes (render_index in simple_shape)
- Allowing outline width to be scaled / not as desired
- How to display layer & folder(if applicable) transforms in properties panel (i.e. do we show layer transform or bounding box, and how is it transformed etc.)
- Clear reference for contributes / artists

**Comment by Keavon** [comment] 2022-04-21 21:18
This should be one of the first things we work on upon switching to the node system. But we can probably live with the UX drawbacks of the current implementation until then. Hopefully nodes can be soon!

**Comment by Keavon** [comment] 2024-02-15 08:37
Duplicate of #1530

**Closed by Keavon** 2024-02-15 08:37 UTC
