### ISSUE TITLE
Make the editor and graph more resilient to crashes

### ISSUE THREAD

**Issue by Keavon** [GraphiteEditor/Graphite#1133] opened 2023-04-15 22:45 UTC
Sandbox various components, like the node graph, in panic handlers. Reload those components instead of having to reload the whole page. Avoid making the document get lost since that's highly destructive to the user and almost always shouldn't be corrupted by whatever bug resulted in the crash, so the document data should most likely be in tact.

**Comment by 0HyperCube** [comment] 2024-01-13 22:39
Duplicate of #1552

**Closed by 0HyperCube** 2024-01-13 22:39 UTC
Labels: Feature, Help Wanted, Architecture, Rust
