### ISSUE TITLE
Re-add text to shape conversion (as a node?)

### ISSUE THREAD

**Issue by Keavon** [GraphiteEditor/Graphite#940] opened 2023-01-02 13:45 UTC
This was disabled when we switched away from the Kurbo vector data format. We might want to make this an explicit user action with a button in the Text area of the Properties panel, since we actually have a Properties panel now. Previously it was an implicit (and potentially accidentally triggered) action by dragging points with the Path tool. Perhaps it can be a button at the bottom called "Convert to Shape Layer". (Eventually this will be a non-destructive node-based workflow, but destructive will do for now.)

**Comment by nine-fox** [comment] 2023-01-15 16:26
Hi, any updates on this? Thanks

**Comment by Keavon** [comment] 2023-01-15 20:41
No updates yet, it's still high priority but our focus has been elsewhere lately. Ideally this should be added within the next sprint (month).

**Comment by nine-fox** [comment] 2023-01-18 11:53
> No updates yet, it's still high priority but our focus has been elsewhere lately. Ideally this should be added within the next sprint (month).

Hi Keavon, Thanks for your reply.

Today I just found another issue probably related to this one - After importing a svg file into canvas, it is displayed as "Image" in Layer Tree. And there is no way to convert that svg into a shape either.

**Comment by Keavon** [comment] 2023-01-18 18:49
That's expected since it's an image, there is no support yet for importing SVG files.

**Comment by nine-fox** [comment] 2023-07-12 06:29
Hi @Keavon , may I ask any updates on this? Thanks

**Comment by Keavon** [comment] 2023-07-12 10:01
The current status is that the node does generate vector path data now, but we don't have a node for storing edits to its input. I don't know precisely when we'll be able to prioritize that since it depends on a few things. So it's probably at least a few months away unless someone wants to volunteer to make vector diffing node and hooking it up to the path tool. Thanks for checking in!

**Comment by 0HyperCube** [comment] 2024-01-27 12:18
Duplicate of #1162

**Closed by 0HyperCube** 2024-01-27 12:18 UTC
Labels: Feature, Rust
