### ISSUE TITLE
[Crash Report] 

### ISSUE THREAD

**Issue by DrRuhe** [GraphiteEditor/Graphite#1998] opened 2024-09-21 12:21 UTC
**Describe the Crash**
Explain clearly what you were doing when the crash occurred.

**Steps To Reproduce**
Describe precisely how the crash occurred, step by step, starting with a new editor window.
1. Open the Graphite editor at https://editor.graphite.rs
2. new document 2400hx1080w
3. create new layer as child of artboard
4. try to create new folder

**Additional Details**

I have 8GB Ram on my laptop, maybe that's too little

**Browser and OS**
Chrome 127, Unix

**Stack Trace**
Copied from the crash dialog in the Graphite editor:

```
panicked at library/alloc/src/raw_vec.rs:25:5:
capacity overflow

Error
    at https://editor.graphite.rs/assets/index-C2OO1iV3.js:713:1149
    at C (https://editor.graphite.rs/assets/index-C2OO1iV3.js:701:214194)
    at Object.handleJsMessage (https://editor.graphite.rs/assets/index-C2OO1iV3.js:701:214342)
    at https://editor.graphite.rs/assets/index-C2OO1iV3.js:702:58144
    at https://editor.graphite.rs/assets/index-C2OO1iV3.js:702:37839
    at It (https://editor.graphite.rs/assets/index-C2OO1iV3.js:702:1944)
    at Id.i.wbg.__wbg_call_8e7cb608789c2528 (https://editor.graphite.rs/assets/index-C2OO1iV3.js:702:37805)
    at graphite_wasm.wasm._ZN13graphite_wasm10editor_api12EditorHandle27send_frontend_message_to_js17h28781e2010b9c4cbE (https://editor.graphite.rs/assets/graphite_wasm_bg-Dl4fdaq4.wasm:wasm-function[2616]:0x5eb657)
    at graphite_wasm.wasm._ZN4core3ops8function2Fn4call17hd63633ebcb753f5fE (https://editor.graphite.rs/assets/graphite_wasm_bg-Dl4fdaq4.wasm:wasm-function[10296]:0x840080)
    at graphite_wasm.wasm._ZN3std9panicking20rust_panic_with_hook17h47bd3d747ed79dc3E (https://editor.graphite.rs/assets/graphite_wasm_bg-Dl4fdaq4.wasm:wasm-function[4953]:0x77b736)
    at graphite_wasm.wasm._ZN4core9panicking9panic_fmt17hb859252f4b513814E (https://editor.graphite.rs/assets/graphite_wasm_bg-Dl4fdaq4.wasm:wasm-function[8138]:0x81d14c)
    at graphite_wasm.wasm._ZN5alloc7raw_vec12handle_error17h604585f1a2687b06E (https://editor.graphite.rs/assets/graphite_wasm_bg-Dl4fdaq4.wasm:wasm-function[9054]:0x82839d)
    at graphite_wasm.wasm._ZN5alloc7raw_vec19RawVec$LT$T$C$A$GT$7reserve21do_reserve_and_handle17h2d4c8e14f6cc7b4fE (https://editor.graphite.rs/assets/graphite_wasm_bg-Dl4fdaq4.wasm:wasm-function[5050]:0x782ca1)
    at graphite_wasm.wasm._ZN15graphite_editor8messages9portfolio8document13utility_types17network_interface20NodeNetworkInterface11chain_width17hc2adc6885b3f3adcE (https://editor.graphite.rs/assets/graphite_wasm_bg-Dl4fdaq4.wasm:wasm-function[1429]:0x4b09fd)
    at graphite_wasm.wasm._ZN15graphite_editor8messages9portfolio8document13utility_types17network_interface20NodeNetworkInterface8position17h1cb1960ce3549dedE (https://editor.graphite.rs/assets/graphite_wasm_bg-Dl4fdaq4.wasm:wasm-function[1829]:0x538d63)
    at graphite_wasm.wasm._ZN15graphite_editor8messages9portfolio8document13utility_types17network_interface20NodeNetworkInterface9set_input17ha50e61912a4a6dd5E (https://editor.graphite.rs/assets/graphite_wasm_bg-Dl4fdaq4.wasm:wasm-function[599]:0x2eba11)
    at graphite_wasm.wasm._ZN15graphite_editor8messages9portfolio8document13utility_types17network_interface20NodeNetworkInterface19move_layer_to_stack17hdbabd0c34537c73dE (https://editor.graphite.rs/assets/graphite_wasm_bg-Dl4fdaq4.wasm:wasm-function[468]:0x26335f)
    at graphite_wasm.wasm._ZN349_$LT$graphite_editor..messages..portfolio..document..document_message_handler..DocumentMessageHandler$u20$as$u20$graphite_editor..utility_traits..MessageHandler$LT$graphite_editor..messages..portfolio..document..document_message..DocumentMessage$C$graphite_editor..messages..portfolio..document..document_message_handler..DocumentMessageData$GT$$GT$15process_message17hc43ecf406e3acbd7E (https://editor.graphite.rs/assets/graphite_wasm_bg-Dl4fdaq4.wasm:wasm-function[309]:0xd714b)
    at graphite_wasm.wasm._ZN325_$LT$graphite_editor..messages..portfolio..portfolio_message_handler..PortfolioMessageHandler$u20$as$u20$graphite_editor..utility_traits..MessageHandler$LT$graphite_editor..messages..portfolio..portfolio_message..PortfolioMessage$C$graphite_editor..messages..portfolio..portfolio_message_handler..PortfolioMessageData$GT$$GT$15process_message17hc1f149df4aa67577E (https://editor.graphite.rs/assets/graphite_wasm_bg-Dl4fdaq4.wasm:wasm-function[302]:0x83b4e)
    at graphite_wasm.wasm._ZN15graphite_editor10dispatcher10Dispatcher14handle_message17h7fa032010f854d53E (https://editor.graphite.rs/assets/graphite_wasm_bg-Dl4fdaq4.wasm:wasm-function[466]:0x2611d8)
    at graphite_wasm.wasm._ZN3std6thread5local17LocalKey$LT$T$GT$4with17hf52b23d8b70afc88E (https://editor.graphite.rs/assets/graphite_wasm_bg-Dl4fdaq4.wasm:wasm-function[4197]:0x6f6e84)
    at graphite_wasm.wasm._ZN13graphite_wasm10editor_api12EditorHandle19widget_value_update17h7e7b864975c8bbb1E (https://editor.graphite.rs/assets/graphite_wasm_bg-Dl4fdaq4.wasm:wasm-function[1776]:0x52d545)
    at graphite_wasm.wasm.editorhandle_widgetValueCommitAndUpdate (https://editor.graphite.rs/assets/graphite_wasm_bg-Dl4fdaq4.wasm:wasm-function[4644]:0x764ef0)
    at ou.widgetValueCommitAndUpdate (https://editor.graphite.rs/assets/index-C2OO1iV3.js:702:4002)
    at P (https://editor.graphite.rs/assets/index-C2OO1iV3.js:747:47799)
    at Array.K (https://editor.graphite.rs/assets/index-C2OO1iV3.js:747:48163)
    at HTMLButtonElement.n (https://editor.graphite.rs/assets/index-C2OO1iV3.js:747:36138)
    at HTMLButtonElement.<anonymous> (https://editor.graphite.rs/assets/index-C2OO1iV3.js:737:75240)
```

**Comment by 0HyperCube** [comment] 2024-09-21 15:55
Thanks for reporting @DrRuhe. The capacity overflow is not related to the available RAM, but the number of items in a Vec. If it goes above `isize::MAX` (`i32::MAX` `2_147_483_647` on wasm32) then you will encounter this error.

I can't replicate this myself. I've tried drawing a rectangle and then pressing <kbd>ctrl</kbd><kbd>g</kbd> to group it. Is this an error that you can consistancy replicate? If so, are there any other steps required?

The error appears to occur within `NodeNetworkInterface::chain_width` (the stack trace doesn't provide any other information as you haven't compiled with debug symbols).

**Comment by DrRuhe** [comment] 2024-09-21 16:04
I cant consistently replicate it. 
My Laptop is not the best, and the site was rather unresponsive for me, so maybe a hiccup caused something to overflow? 

Otherwise feel free to close this

**Comment by Keavon** [comment] 2024-09-24 01:34
Please keep commenting with further information if you're able to find more useful details or a way to consistently reproduce this. But in the meanwhile, I'm going to close this because there's little we can do without a consistent reproduction. But if you do manage to find that, please post it here and we can investigate further.

**Closed by Keavon** 2024-09-24 01:34 UTC
