### ISSUE TITLE
[Crash Report] unwrap on an `Err` value: LayerNotFound...

### ISSUE THREAD

**Issue by adsick** [GraphiteEditor/Graphite#724] opened 2022-07-13 11:01 UTC
**Describe the Crash**
Explain clearly what you were doing when the crash occurred.

**Steps To Reproduce**
Describe precisely how the crash occurred, step by step, starting with a new editor window.
1. Open the Graphite Editor at https://editor.graphite.rs
2. create a box
3. pick a Path tool (A)
4. modify the box
5. Ctrl + Z two times
6. crash
7. lol

**Additional Details**
Provide any further information or context that you think would be helpful in fixing the issue. Screenshots or video can be linked or attached to this issue.

**Browser and OS**
Firefox 102, Unix

**Stack Trace**
Copied from the crash dialog in the Graphite Editor:

```
panicked at 'called `Result::unwrap()` on an `Err` value: LayerNotFound([5868149752444798564])', editor/src/viewport_tools/vector_editor/vector_shape.rs:149:119

228/Pt/<@https://editor.graphite.rs/js/app.efdb937e.js:9:1004
n@https://editor.graphite.rs/js/app.efdb937e.js:1:6593
228/bt/e<@https://editor.graphite.rs/js/app.efdb937e.js:1:7096
738/</E_/<@https://editor.graphite.rs/js/123.4faffd93.js:1:13894
M@https://editor.graphite.rs/js/123.4faffd93.js:1:5560
E_@https://editor.graphite.rs/js/123.4faffd93.js:1:13860
@https://editor.graphite.rs/456f326e12545a37.module.wasm:wasm-function[2080]:0x1863f9
@https://editor.graphite.rs/456f326e12545a37.module.wasm:wasm-function[812]:0x13a3b8
@https://editor.graphite.rs/456f326e12545a37.module.wasm:wasm-function[769]:0x13548c
@https://editor.graphite.rs/456f326e12545a37.module.wasm:wasm-function[926]:0x14687b
@https://editor.graphite.rs/456f326e12545a37.module.wasm:wasm-function[2683]:0x18be52
@https://editor.graphite.rs/456f326e12545a37.module.wasm:wasm-function[1523]:0x173541
@https://editor.graphite.rs/456f326e12545a37.module.wasm:wasm-function[1758]:0x17dd00
@https://editor.graphite.rs/456f326e12545a37.module.wasm:wasm-function[2234]:0x1890af
@https://editor.graphite.rs/456f326e12545a37.module.wasm:wasm-function[2239]:0x1891d2
@https://editor.graphite.rs/456f326e12545a37.module.wasm:wasm-function[1834]:0x180368
@https://editor.graphite.rs/456f326e12545a37.module.wasm:wasm-function[214]:0xbb4c2
@https://editor.graphite.rs/456f326e12545a37.module.wasm:wasm-function[151]:0x96ded
@https://editor.graphite.rs/456f326e12545a37.module.wasm:wasm-function[665]:0x127bf9
@https://editor.graphite.rs/456f326e12545a37.module.wasm:wasm-function[83]:0x56275
@https://editor.graphite.rs/456f326e12545a37.module.wasm:wasm-function[137]:0x8c1ab
@https://editor.graphite.rs/456f326e12545a37.module.wasm:wasm-function[623]:0x121ba8
@https://editor.graphite.rs/456f326e12545a37.module.wasm:wasm-function[723]:0x12f96a
@https://editor.graphite.rs/456f326e12545a37.module.wasm:wasm-function[1365]:0x16a61a
@https://editor.graphite.rs/456f326e12545a37.module.wasm:wasm-function[1887]:0x181a95
on_key_down@https://editor.graphite.rs/js/123.4faffd93.js:1:8554
228/i/get/<@https://editor.graphite.rs/js/app.efdb937e.js:1:292
g@https://editor.graphite.rs/js/app.efdb937e.js:1:15231
action@https://editor.graphite.rs/js/app.efdb937e.js:1:13897
```

nice auto reporting btw

**Comment by RahulHi** [comment] 2022-07-15 02:24
Sure! I can reproduce this bug in editor.graphite.rs, but I can not in dev.graphite.rs or locally.

When I was attempting to fix the crash caused by the properties panel not being able to find the previously selected layer after an undo action removed the layer (details in PR #716), the crashing stopped after I merged the broadcast system (PR #692), which I assumed is what solved that crash. Perhaps that solved this issue crash as well? @Keavon

**Comment by Keavon** [comment] 2022-07-15 02:26
Ah, if it's not in dev.graphite.rs, that just means it's already fixed. I think the latest master is stable enough to update the live release. I was being a little conservative because I assumed there would be further issues arising from the big refactor which touched so many systems. Closing as already fixed (and I'll update the release now).

**Closed by Keavon** 2022-07-15 02:26 UTC
Labels: Available, Rust, P-High, Crash

**Comment by Keavon** [comment] 2022-07-15 03:10
But the new problem, @RahulHi, is that every mouse movement when an anchor point in the path is moved around with the Path tool ends up adding to the history. Not the final position where you let go, but every mouse move gets thrown into the queue.
