### ISSUE TITLE
Save work periodically to reduce loss from crashes

### ISSUE THREAD

**Issue by Keavon** [GraphiteEditor/Graphite#929] opened 2022-12-29 12:15 UTC
Try and find more times it would make sense to save, since it does likely take a little while to serialize and write the document which should ideally not cause annoying freezes for the user. We should aim to hopefully never make the user lose more than, say, 30 seconds of work.

Also, closing/reloading the page sometimes doesn't save correctly (maybe it doesn't have enough time if the editor is being slow or the document is big?). This should help in that case. Investigating the actual cause would also be nice.

Alternatively, now that we have moved toward the full node graph, it may be feasible to take a VS Code style approach where everything you do is saved in real time but the `*` isn't updated until you download the file. It might even be better to remove the `*` entirely, since whether you download the file isn't really that useful, except when #747 is in use (in a compatible browser and enabled by the user).

**Comment by iacore** [comment] 2024-01-11 00:29
> Also, closing/reloading the page sometimes doesn't save correctly

This is a pop-up window when I try to close the page. Is that not enough to block the page from being closed while unsaved changes exist?

**Comment by Comeza** [comment] 2024-01-15 11:18
Addressed in #1580

**Comment by Comeza** [comment] 2024-01-17 01:12
> it may be feasible to take a VS Code style approach where everything you do is saved in real time but the * isn't updated until you download the file

I don't know how smart this approach would be, as a document can probably get quite complex, and serializing it on every change seems inefficient.

A better approach might be to wait for the user to idle and then save the document. The problem is, that data will be lost if the editor crashes while the user has not been idle for a long time.
So for me it seems the best approach is just to save the doc periodically.

**Closed** 2024-02-20 03:23 UTC
Labels: Feature, Web, Rust
