### ISSUE TITLE
Crash when selecting node with Widget::NumberInput in properties panel

### ISSUE THREAD

**Issue by adamgerhant** [GraphiteEditor/Graphite#1761] opened 2024-05-27 16:57 UTC
When the cursor is in a text box, such as in the Text node, and the transform node is clicked, the editor crashes. This is due to the Value::String not being reset when switching nodes, so the string value from the text box gets passed to the number input, which causes a panic.

**Comment by 0HyperCube** [comment] 2024-05-27 20:54
Note that this doesn't happen in firefox and only in chromium. Also the text node needs to be selected in the graph with the cursor in the text box before clicking on the transform node.

**Comment by Keavon** [comment] 2024-05-27 20:56
Yeah, I've run into other bugs where Firefox and Chrome had different event ordering. I can try looking into this. Thanks for that extra data @0HyperCube.

**Comment by Keavon** [comment] 2024-07-12 22:35
0. (Use a Chromium browser)
1. Draw something with the Text tool
2. Open the node graph
3. Click the text node so it's the only selection in the graph
4. Select the text field in the Properties panel so your text cursor is somewhere that'd allow you to type
5. Click on a different node, such as Transform, Fill, or Stroke

**Comment by Keavon** [comment] 2024-07-12 22:48
I found a more general issue:
0. (This happens in both Firefox and Chromium browsers)
1. Draw a rectangle with some fill color, so it'll be visible even without a stroke
2. Open the graph
3. Select the Stroke node, click the Weight, set it to 0, and hit enter because the bug only works when the initial value of the field is 0
4. Select that Weight field again and type something like 500 but don't hit enter yet
5. Click the Transform node and you'll find that it has applied the 500 to the rotation as 500°

**Comment by prestonbourne** [comment] 2024-11-30 22:02
hello @Keavon 
is this still an issue? 
when I tried to follow the steps in the most recent comment, i was unable to reproduce

> I found a more general issue: 0. (This happens in both Firefox and Chromium browsers)
> 
> 1. Draw a rectangle with some fill color, so it'll be visible even without a stroke
> 2. Open the graph
> 3. Select the Stroke node, click the Weight, set it to 0, and hit enter because the bug only works when the initial value of the field is 0
> 4. Select that Weight field again and type something like 500 but don't hit enter yet
> 5. Click the Transform node and you'll find that it has applied the 500 to the rotation as 500°

**Comment by Keavon** [comment] 2024-12-24 00:35
I *think* I recall when we might have fixed this or something related to this (it involved how the widgets were displaying the unit, such as `°`, across widgets when clicking between nodes). I also can't reproduce the issue, so I'm going to close this. Thanks for bringing this up @prestonbourne.

**Closed by Keavon** 2024-12-24 00:35 UTC
Labels: Good First Issue, Crash
