### ISSUE TITLE
Selecting two handles with the Path tool creates oddity that may crash the software

### ISSUE THREAD

**Issue by Intuos5** [GraphiteEditor/Graphite#1554] opened 2024-01-07 11:49 UTC
When I select two handles of a nod with the node tool while pressing shift, if I then drag the node, it does this:

https://github.com/GraphiteEditor/Graphite/assets/63149655/3dfcb105-19dd-4209-b1d4-1751b3c4c8e1

In other software, the selection of the second handle is ignored to circumvent such a situation.
This is the error log: 

panicked at node-graph/interpreted-executor/src/node_registry.rs:425:76:
index out of bounds: the len is 1 but the index is 1

S1/<@https://editor.graphite.rs/assets/index-18c12830.js:29:1143
h@https://editor.graphite.rs/assets/index-18c12830.js:17:34203
handleJsMessage@https://editor.graphite.rs/assets/index-18c12830.js:17:34351
a1/e<@https://editor.graphite.rs/assets/index-18c12830.js:18:33012
s1/o.wbg.__wbg_call_4c92f6aec1e1d6e6/<@https://editor.graphite.rs/assets/index-18c12830.js:18:29449
rt@https://editor.graphite.rs/assets/index-18c12830.js:18:1233
s1/o.wbg.__wbg_call_4c92f6aec1e1d6e6@https://editor.graphite.rs/assets/index-18c12830.js:18:29415
@https://editor.graphite.rs/assets/graphite_wasm_bg-881d868d.wasm:wasm-function[1475]:0x3b6b84
@https://editor.graphite.rs/assets/graphite_wasm_bg-881d868d.wasm:wasm-function[4066]:0x4d6f91
@https://editor.graphite.rs/assets/graphite_wasm_bg-881d868d.wasm:wasm-function[3689]:0x4bf8dc
@https://editor.graphite.rs/assets/graphite_wasm_bg-881d868d.wasm:wasm-function[6083]:0x55468e
@https://editor.graphite.rs/assets/graphite_wasm_bg-881d868d.wasm:wasm-function[4873]:0x4f7a48
@https://editor.graphite.rs/assets/graphite_wasm_bg-881d868d.wasm:wasm-function[2524]:0x460d25
@https://editor.graphite.rs/assets/graphite_wasm_bg-881d868d.wasm:wasm-function[373]:0x1e5560
@https://editor.graphite.rs/assets/graphite_wasm_bg-881d868d.wasm:wasm-function[1738]:0x3f1e7c
@https://editor.graphite.rs/assets/graphite_wasm_bg-881d868d.wasm:wasm-function[6727]:0x55db41
Qc@https://editor.graphite.rs/assets/index-18c12830.js:18:433
s@https://editor.graphite.rs/assets/index-18c12830.js:18:115

**Comment by Keavon** [comment] 2024-01-07 11:57
Regarding the crash, it looks like you've coincidentally hit an issue we are dealing with at the moment that happens in many separate occasions when dragging. We think it's a race condition. It happens when dragging a line, or even just panning the document, but it's hard to reproduce. The weird vector handle selection behavior is separate and could probably use some love in the future (anyone reading this, feel free to get in touch with me to figure out the intended multi-handle movement behavior if you're interested in contributing a behavioral change). I'm going to close this as a duplicate of the current crash since this is just a specific manifestation of it through dragging. Thanks for the report!

**Closed by Keavon** 2024-01-07 11:57 UTC
