### ISSUE TITLE
Can draw path point on top of vertical scroll bar

### ISSUE THREAD

**Issue by mickvangelderen** [GraphiteEditor/Graphite#1349] opened 2023-08-02 09:44 UTC
Can draw path point on top of vertical scroll bar. I wanted to move the viewport but ended up adding a new path segment too. Used the mobile web version.

**Comment by Keavon** [comment] 2023-08-02 15:47
Are you talking about the Pen tool? I can't reproduce that based on my interpretation of your description. Can you please provide a highly detailed step-by-step reproduction, or a video?

**Comment by Keavon** [comment] 2023-08-10 21:59
I'm going to close this until more information is provided. Please follow up and then I can reopen this.

**Closed by Keavon** 2023-08-10 21:59 UTC

**Comment by mickvangelderen** [comment] 2023-09-11 15:00
Just noticed this. Maybe it's fixed then.
