### ISSUE TITLE
Fix Vue warning when displaying a transparent ColorInput

### ISSUE THREAD

**Issue by 0HyperCube** [GraphiteEditor/Graphite#614] opened 2022-04-22 20:52 UTC
Vue generates a warning when displaying transparent ColourInput (`frontend/src/components/widgets/inputs/ColorInput.vue 85:18`)  because it is expecting a `type: String` but gets `undefined`. The `type` json entry cannot be a union, so perhaps it should be an `Object` that is then limited by the `as PropType<string | undefined>`?

**Comment by Keavon** [comment] 2022-05-29 17:48
I can't reproduce this (in dev mode) by setting a color to transparent. Is it perhaps fixed?

**Comment by Keavon** [comment] 2022-05-29 18:27
Closing it for now, but reopen if it's still an issue.

**Closed by Keavon** 2022-05-29 18:27 UTC
Labels: Good First Issue, Available, Cleanup, Web, P-Low
