### ISSUE TITLE
Using the text tool on firefox for android zooms page in

### ISSUE THREAD

**Issue by bjorn3** [GraphiteEditor/Graphite#543] opened 2022-02-12 19:57 UTC
It isn't possible to zoom out again afterwards.

**Comment by bjorn3** [comment] 2022-02-12 19:57
Even refreshing the page doesn't zoom out again. Had to open it in a new page.

**Comment by 0HyperCube** [comment] 2022-02-20 09:16
@bjorn3 It sounds like a browser bug and I can't seem to replicate this. Does the following code also cause the issue?
```html
<svg width="300px" height="300px">
  <g transform="scale(2)">
    <foreignObject width="100" height="100">
      <div style="color: black;" contenteditable>Hello world<div>
    </foreignObject>
  </g>
</svg>
```

**Comment by Keavon** [comment] 2022-02-20 10:38
I also can't reproduce this on Firefox for Android.

**Comment by bjorn3** [comment] 2022-02-20 12:32
I can reproduce this by selecting the text tool, clicking somewhere, typing some text and then clicking somewhere else to dismiss the keyboard, clicking somewhere again to show the keyboard and in some cases repeating this a couple of times. I don't think it is a browser bug that it zooms in. This is behavior is useful when text fields are very small. The problem is that I can't zoom out again. I noticed that it doesn't happen when I disable allow zooming on all sites in the accessibility settings though.

**Comment by 0HyperCube** [comment] 2022-02-21 08:52
@bjorn3 I meant that perhaps the not zooming out was a browser bug. I cannot seem to find where this behaviour is documented so I can't tell why this is happening.

**Comment by Keavon** [comment] 2022-10-21 01:17
@bjorn3 could you please confirm if this is still a problem?

**Comment by bjorn3** [comment] 2022-10-21 11:02
Still happens

**Comment by 0HyperCube** [comment] 2023-07-01 09:09
I think this might be fixed now as we no longer use a text input inside a foreign object. Would you mind testing this @bjorn3?

**Comment by bjorn3** [comment] 2023-07-01 11:51
It doesn't zoom in anymore, but now the virtual keyboard pops up and immediately disappears again. The statusbar is still in the state it should be when you can type text though.

**Closed** 2023-07-01 16:26 UTC
Labels: Bug, Web, Rust
