### ISSUE TITLE
[Crash Report] 

### ISSUE THREAD

**Issue by factor8** [GraphiteEditor/Graphite#1562] opened 2024-01-12 20:46 UTC
**Describe the Crash**
Explain clearly what you were doing when the crash occurred.

**Steps To Reproduce**
Describe precisely how the crash occurred, step by step, starting with a new editor window.
1. Open the Graphite editor at https://editor.graphite.rs
2. 
3. 
4. 
5. 

**Additional Details**
Provide any further information or context that you think would be helpful in fixing the issue. Screenshots or video can be linked or attached to this issue.

**Browser and OS**
Chrome 120, Windows 10 or 11

**Stack Trace**
Copied from the crash dialog in the Graphite editor:

```
panicked at node-graph/interpreted-executor/src/node_registry.rs:425:76:
index out of bounds: the len is 1 but the index is 1

Error
    at https://editor.graphite.rs/assets/index-c18f9d18.js:29:1143
    at h (https://editor.graphite.rs/assets/index-c18f9d18.js:17:34203)
    at Object.handleJsMessage (https://editor.graphite.rs/assets/index-c18f9d18.js:17:34351)
    at https://editor.graphite.rs/assets/index-c18f9d18.js:18:33012
    at https://editor.graphite.rs/assets/index-c18f9d18.js:18:29449
    at rt (https://editor.graphite.rs/assets/index-c18f9d18.js:18:1233)
    at o.wbg.__wbg_call_4c92f6aec1e1d6e6 (https://editor.graphite.rs/assets/index-c18f9d18.js:18:29415)
    at https://editor.graphite.rs/assets/graphite_wasm_bg-f097a9a7.wasm:wasm-function[1474]:0x3b62e0
    at https://editor.graphite.rs/assets/graphite_wasm_bg-f097a9a7.wasm:wasm-function[4069]:0x4d6938
    at https://editor.graphite.rs/assets/graphite_wasm_bg-f097a9a7.wasm:wasm-function[3692]:0x4bf2dd
    at https://editor.graphite.rs/assets/graphite_wasm_bg-f097a9a7.wasm:wasm-function[6085]:0x55428d
    at https://editor.graphite.rs/assets/graphite_wasm_bg-f097a9a7.wasm:wasm-function[4876]:0x4f73ef
    at https://editor.graphite.rs/assets/graphite_wasm_bg-f097a9a7.wasm:wasm-function[2526]:0x460615
    at https://editor.graphite.rs/assets/graphite_wasm_bg-f097a9a7.wasm:wasm-function[373]:0x1e55ff
    at https://editor.graphite.rs/assets/graphite_wasm_bg-f097a9a7.wasm:wasm-function[1738]:0x3f17fa
    at https://editor.graphite.rs/assets/graphite_wasm_bg-f097a9a7.wasm:wasm-function[6729]:0x55d740
    at Qc (https://editor.graphite.rs/assets/index-c18f9d18.js:18:433)
    at s (https://editor.graphite.rs/assets/index-c18f9d18.js:18:115)
```

**Comment by 0HyperCube** [comment] 2024-01-12 21:23
Thanks for the report @factor8 - I believe this to be a duplicate of #1561 whereby the node graph is corrupted as we try to execute it. Could you perhaps clarify which tool you were using at the time of the crash? Thanks.

**Comment by factor8** [comment] 2024-01-12 21:26
Yes, I was just demoing the software for the first time and when it asked to report the crash I simply clicked all the way through to submit without reviewing any other issues.

I am almost certain the tool was the node editor and I was dragging a point for the second or third time on a pentagon shape... I'll pay closer attention next time but I'm 85% sure that was the action.

**Comment by 0HyperCube** [comment] 2024-01-13 17:12
Thanks - I believe it is fixed in https://dev.graphite.rs/ - could you confirm this? Thanks again for reporting @factor8.

**Closed** 2024-01-17 16:34 UTC
