### ISSUE TITLE
Export with "All Artwork" may use incorrect bounds

### ISSUE THREAD

**Issue by solodeveloping** [GraphiteEditor/Graphite#2113] opened 2024-11-20 11:12 UTC
Hello,

For starter, I want to thank you for you work, it's very cool :)

When exporting to .png, the output appear cropped at the bottom.

I choosed .png, "All Artwork".

It's also appear cropped in .svg actually, which is strange.

![image](https://github.com/user-attachments/assets/49cf5db5-8684-4b7b-9370-8fc2ae727a29)

<details><summary><em>(Additional unactionable bug report)</em></summary>
<p>

### Bug 2 : color artifacts when exporting

When exporting to .png, using "All Artwork", some weird colors appeared in some pixels.

I was using Firefox in a private window when it occurred, I was not able to reproduce it in Chrome or Firefox, or Firefox in a private window when reimporting the file afterward (or in Chrome in a private window).

![icons1x](https://github.com/user-attachments/assets/68476077-64f2-451f-a8df-4a6562a93bdd)

(The image look weird, if you don't use dark mode, here because the file has white shapes, and the background is white).

Thank you in advance,

</p>
</details>

**Comment by Keavon** [comment] 2024-11-21 06:06
Thanks for the report. Are you at liberty to share your document for testing bug 1? Regarding bug 2, it sounds like even you weren't able to reproduce it outside of the one time it occurred, so I couldn't even really speculate where the problem arose. It sounds like an issue likely in the Firefox SVG renderer, which we'll be replacing in the render pipeline with our Vello render engine within the next few months. I'll edit your issue to hide bug 2 since it's not actionable but will be solved with the new render engine, and update/triage your issue regarding the All Artwork export issue. Thank you!

**Comment by solodeveloping** [comment] 2024-11-27 15:20
Hi,

Yes, I forgot to link the document, you can find it here https://opengameart.org/content/fantasy-class-icons-0

**Comment by Keavon** [comment] 2024-12-24 00:12
Closing as duplicate of #2129 (since that one is clearer at describing the problem so it'll be more likely to get fixed).

**Closed by Keavon** 2024-12-24 00:12 UTC
Labels: Bug, Rust
