### ISSUE TITLE
Switch to an attribute-based procedural vector format

### ISSUE THREAD

**Issue by Keavon** [GraphiteEditor/Graphite#811] opened 2022-10-23 07:39 UTC

**Comment by 0HyperCube** [comment] 2023-12-04 22:45
Duplicate of #1162

**Comment by Keavon** [comment] 2023-12-04 22:51
Sorry for not writing a more descriptive explanation about each of these two issues. #1162 refers to a short-term goal of encoding a diff for our existing SVG-based vector format. This issue refers to a series of upcoming design meetings and refactors that will move us from the MVP format we're using today to something supporting arbitrary bezier meshes (like the OBJ 3D format but with beziers instead of straight edge connections) and a way of laying out the data in a way that can be operated on procedurally like in Houdini and Blender geometry nodes. This issue refers to this item on the roadmap:

![image](https://github.com/GraphiteEditor/Graphite/assets/4388688/ec23e24d-a9a5-4a54-8892-9f76b029fa18)

**Closed** 2024-03-09 18:27 UTC
Labels: Feature, Architecture, Rust, Design
