### ISSUE TITLE
Clicking in number input and dragging selects from start to mouse in Firefox

### ISSUE THREAD

**Issue by 0HyperCube** [GraphiteEditor/Graphite#1156] opened 2023-04-24 17:12 UTC
Clicking in a number input and dragging slightly causes a selection to be made from the start of the number to the user's mouse.

This can be frustrating as the user will probably delete the significant figures and the decimal point, so they are left with a very large random number (causing the shape to fly off somewhere).

A better behaviour would be to either be to a) always select the entire number when the user clicks and slightly drags or b) to select from the start of the drag to the end of the drag (rather then from the start of the number).

**Comment by Keavon** [comment] 2023-09-09 20:40
This is a Firefox-only issue. The problem is that, if you intend to click to replace the text, you might click and drag by a pixel by mistake. This causes it to select a portion of the text for replacement instead of all the text, giving you an unexpected bunch of numbers at the end.

**Comment by asuru56** [comment] 2023-10-15 06:48
Hey , this issue is not reproducible in firefox


![Image](https://github.com/GraphiteEditor/Graphite/assets/65706338/f2da47a6-ff5b-45ea-ab77-ec9bfe1304f0)

**Comment by Keavon** [comment] 2023-10-17 00:37
I just confirmed it's still an issue on the latest FF version (118). All you do to reproduce it is click and drag from over the top of some numbers and then keep dragging left or right of your mousedown position.

**Comment by Keavon** [comment] 2023-11-21 23:59
Closing this as a duplicate/insubstantial subset of #313.

**Closed by Keavon** 2023-11-21 23:59 UTC
Labels: Bug, Good First Issue, Web, Paper Cut
